/* 
 * File:   mcal_interrupt_gen_cfg.h
 * Author: M0rE
 *
 * Created on January 8, 2024, 12:31 AM
 */

#ifndef MCAL_INTERRUPT_GEN_CFG_H
#define	MCAL_INTERRUPT_GEN_CFG_H

#define FEATURE_ENABLED 1
//#define INTERRUPT_PRIORITY_LEVELS           FEATURE_ENABLED
#define EXTERNAL_INTERRUPT_ONCHANGE_ENABLE  FEATURE_ENABLED
#define EXTERNAL_INTERRUPT_INTx_ENABLE      FEATURE_ENABLED
#define ADC_INTERRUPT_FEATURE_ENABLE        FEATURE_ENABLED

#endif	/* MCAL_INTERRUPT_GEN_CFG_H */

